# -*- coding: utf-8 -*-
"""Test_ML_mezzora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/141AAlmAet28iHu82jWlks15ubxvAi3J9
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
!pip -q install tensorflow

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.neural_network import MLPRegressor
from google.colab import files
import io

uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[filename]))
df.head()

# conversione tempo e ordinamento
df["time"] = pd.to_datetime(df["time"])
df = df.sort_values("time").reset_index(drop=True)

print(df.head())
print(df.shape)

print("Colonne:", df.columns.tolist())
print("\nValori mancanti:")
print(df.isna().sum())

print("\nTipi:")
print(df.dtypes)

df["delta_min"] = df["time"].diff().dt.total_seconds() / 60

print(df[["time", "delta_min"]].head(10))

print("\nDistribuzione dei delta temporali:")
print(df["delta_min"].value_counts(dropna=False).sort_index())

allowed_steps = {5, 10, 15}

df["delta_min_rounded"] = df["delta_min"].round()

# la prima riga non deve creare un gap artificiale
df["delta_min_rounded"] = df["delta_min_rounded"].fillna(5)

# is_gap = True solo se il salto NON è tra quelli ammessi
df["is_gap"] = ~df["delta_min_rounded"].isin(allowed_steps)

print(df[["time", "delta_min", "delta_min_rounded", "is_gap"]].head(15))

df["segmentid"] = df["is_gap"].cumsum()

segmentsizes = (
    df.groupby("segmentid")
      .size()
      .reset_index(name="length")
      .sort_values("length", ascending=False)
      .reset_index(drop=True)
)

print(segmentsizes.head(20))
print("\nNumero segmenti totali:", df["segmentid"].nunique())

windowsize = 30          # 30 misure passate
horizon = 6              # 6 step * 5 minuti = 30 minuti dopo
minlen = windowsize + horizon

validsegments = segmentsizes.loc[segmentsizes["length"] >= minlen, "segmentid"]

dfvalid = df[df["segmentid"].isin(validsegments)].copy().reset_index(drop=True)

print("Shape dfvalid:", dfvalid.shape)
print("Numero segmenti validi:", dfvalid["segmentid"].nunique())
print("Lunghezza minima richiesta:", minlen)

featurecols = ["temp", "hum", "lux"]
targetcol = "temp"

X, y, metatime = [], [], []

for segid, segdf in dfvalid.groupby("segmentid"):
    segdf = segdf.sort_values("time").reset_index(drop=True)

    values = segdf[featurecols].values
    target = segdf[targetcol].values
    times = segdf["time"].values

    for i in range(len(segdf) - windowsize - horizon + 1):
        X.append(values[i:i + windowsize])
        y.append(target[i + windowsize + horizon - 1])
        metatime.append(times[i + windowsize + horizon - 1])

X = np.array(X)
y = np.array(y)
metatime = np.array(metatime)

print("Shape di X:", X.shape)
print("Shape di y:", y.shape)
print("Prime date target:", metatime[:5])

Xflat = X.reshape(X.shape[0], X.shape[1] * X.shape[2])

print("Shape di Xflat:", Xflat.shape)

splitidx = int(len(Xflat) * 0.8)

Xtrain = Xflat[:splitidx]
Xtest = Xflat[splitidx:]

ytrain = y[:splitidx]
ytest = y[splitidx:]

timetrain = metatime[:splitidx]
timetest = metatime[splitidx:]

print("Train:", Xtrain.shape, ytrain.shape)
print("Test :", Xtest.shape, ytest.shape)

# =========================================================
# metriche di valutazione
# =========================================================

def regression_metrics(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    return mae, rmse, r2

# =========================================================
# Baseline naive
# =========================================================

naive_preds = Xtest[:, -3]

print("Prime naive preds:", naive_preds[:5])
print("Prime ytest      :", ytest[:5])

naive_mae, naive_rmse, naive_r2 = regression_metrics(ytest, naive_preds)

print("Naive baseline")
print("MAE :", naive_mae)
print("RMSE:", naive_rmse)
print("R2  :", naive_r2)

# =========================================================
# Linear Regression
# =========================================================

lin_model = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LinearRegression())
])

lin_model.fit(Xtrain, ytrain)
lin_preds = lin_model.predict(Xtest)

lin_mae, lin_rmse, lin_r2 = regression_metrics(ytest, lin_preds)

print("Linear Regression")
print("MAE :", lin_mae)
print("RMSE:", lin_rmse)
print("R2  :", lin_r2)

# =========================================================
# Random Forest
# =========================================================

rf_model = RandomForestRegressor(
    n_estimators=300,
    max_depth=10,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(Xtrain, ytrain)
rf_preds = rf_model.predict(Xtest)

rf_mae, rf_rmse, rf_r2 = regression_metrics(ytest, rf_preds)

print("Random Forest")
print("MAE :", rf_mae)
print("RMSE:", rf_rmse)
print("R2  :", rf_r2)

# =========================================================
# MLP
# =========================================================

mlp_model = Pipeline([
    ("scaler", StandardScaler()),
    ("model", MLPRegressor(
        hidden_layer_sizes=(128, 64),
        activation="relu",
        solver="adam",
        alpha=1e-4,
        learning_rate_init=1e-3,
        max_iter=500,
        early_stopping=True,
        validation_fraction=0.1,
        n_iter_no_change=20,
        random_state=42
    ))
])

mlp_model.fit(Xtrain, ytrain)
mlp_preds = mlp_model.predict(Xtest)

mlp_mae, mlp_rmse, mlp_r2 = regression_metrics(ytest, mlp_preds)

print("MLP")
print("MAE :", mlp_mae)
print("RMSE:", mlp_rmse)
print("R2  :", mlp_r2)

# =========================================================
# Ridge Regression
# =========================================================

from sklearn.linear_model import Ridge

ridge_model = Pipeline([
    ("scaler", StandardScaler()),
    ("model", Ridge(alpha=1.0))
])

ridge_model.fit(Xtrain, ytrain)
ridge_preds = ridge_model.predict(Xtest)

ridge_mae, ridge_rmse, ridge_r2 = regression_metrics(ytest, ridge_preds)

print("Ridge Regression")
print("MAE :", ridge_mae)
print("RMSE:", ridge_rmse)
print("R2  :", ridge_r2)

# =========================================================
# Gradient Boosting
# =========================================================

from sklearn.ensemble import GradientBoostingRegressor

gbr_model = GradientBoostingRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

gbr_model.fit(Xtrain, ytrain)
gbr_preds = gbr_model.predict(Xtest)

gbr_mae, gbr_rmse, gbr_r2 = regression_metrics(ytest, gbr_preds)

print("Gradient Boosting")
print("MAE :", gbr_mae)
print("RMSE:", gbr_rmse)
print("R2  :", gbr_r2)

# =========================================================
# LSTM
# =========================================================

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

splitidx_lstm = int(len(X) * 0.8)

Xtrain_lstm = X[:splitidx_lstm]
Xtest_lstm = X[splitidx_lstm:]

ytrain_lstm = y[:splitidx_lstm]
ytest_lstm = y[splitidx_lstm:]

print("Train LSTM:", Xtrain_lstm.shape, ytrain_lstm.shape)
print("Test LSTM :", Xtest_lstm.shape, ytest_lstm.shape)

n_features = Xtrain_lstm.shape[2]

x_scaler = StandardScaler()
Xtrain_2d = Xtrain_lstm.reshape(-1, n_features)
Xtest_2d = Xtest_lstm.reshape(-1, n_features)

Xtrain_scaled = x_scaler.fit_transform(Xtrain_2d).reshape(Xtrain_lstm.shape)
Xtest_scaled = x_scaler.transform(Xtest_2d).reshape(Xtest_lstm.shape)

y_scaler = StandardScaler()
ytrain_scaled = y_scaler.fit_transform(ytrain_lstm.reshape(-1, 1)).ravel()
ytest_scaled = y_scaler.transform(ytest_lstm.reshape(-1, 1)).ravel()

tf.random.set_seed(42)
np.random.seed(42)

lstm_model = Sequential([
    Input(shape=(Xtrain_scaled.shape[1], Xtrain_scaled.shape[2])),
    LSTM(64),
    Dropout(0.2),
    Dense(32, activation="relu"),
    Dense(1)
])

lstm_model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=15,
    restore_best_weights=True
)

history = lstm_model.fit(
    Xtrain_scaled,
    ytrain_scaled,
    validation_split=0.1,
    epochs=100,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

lstm_preds_scaled = lstm_model.predict(Xtest_scaled).ravel()
lstm_preds = y_scaler.inverse_transform(lstm_preds_scaled.reshape(-1, 1)).ravel()

lstm_mae, lstm_rmse, lstm_r2 = regression_metrics(ytest_lstm, lstm_preds)

print("LSTM")
print("MAE :", lstm_mae)
print("RMSE:", lstm_rmse)
print("R2  :", lstm_r2)

# =========================================================
# Comparazione risultati
# =========================================================

results_df = pd.DataFrame([
    {"model": "NaiveLastTemp",    "mae": naive_mae,   "rmse": naive_rmse,   "r2": naive_r2},
    {"model": "LinearRegression", "mae": lin_mae,     "rmse": lin_rmse,     "r2": lin_r2},
    {"model": "Ridge",            "mae": ridge_mae,   "rmse": ridge_rmse,   "r2": ridge_r2},
    {"model": "RandomForest",     "mae": rf_mae,      "rmse": rf_rmse,      "r2": rf_r2},
    {"model": "GradientBoosting", "mae": gbr_mae,     "rmse": gbr_rmse,     "r2": gbr_r2},
    {"model": "MLP",              "mae": mlp_mae,     "rmse": mlp_rmse,     "r2": mlp_r2},
    {"model": "LSTM",             "mae": lstm_mae,    "rmse": lstm_rmse,    "r2": lstm_r2},
]).sort_values("rmse").reset_index(drop=True)

results_df