# -*- coding: utf-8 -*-
"""Test_ML_deltaT_mezzora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ENcEhJXhA82V80rAjFd6bZ1tpeXO9jTl
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.neural_network import MLPRegressor
import io

df = pd.read_csv("dataset_ML.csv")
df.head()

# conversione tempo e ordinamento
df["time"] = pd.to_datetime(df["time"])
df = df.sort_values("time").reset_index(drop=True)

print(df.head())
print(df.shape)

print("Shape:", df.shape)
print("Colonne:", df.columns.tolist())
print("\nInfo dataset:")
print(df.info())

if "timestamp" in df.columns:
    df = df.rename(columns={"timestamp": "time"})

df["time"] = pd.to_datetime(df["time"], utc=True)
df = df.sort_values("time").reset_index(drop=True)

df.head()

print(df.isna().sum())

df["delta_min"] = df["time"].diff().dt.total_seconds() / 60

print(df[["time", "delta_min"]].head(10))
print("\nDistribuzione delta_min:")
print(df["delta_min"].value_counts(dropna=False).sort_index())

allowed_steps = {5, 10, 15}

df["delta_min_rounded"] = df["delta_min"].round().fillna(5)
df["is_gap"] = ~df["delta_min_rounded"].isin(allowed_steps)

print(df[["time", "delta_min", "delta_min_rounded", "is_gap"]].head(15))

df["segmentid"] = df["is_gap"].cumsum()

segmentsizes = (
    df.groupby("segmentid")
      .size()
      .reset_index(name="length")
      .sort_values("length", ascending=False)
      .reset_index(drop=True)
)

print(segmentsizes.head(20))
print("\nNumero segmenti:", df["segmentid"].nunique())

windowsize = 30
horizon = 6              # 6 step da 5 minuti = 30 minuti
minlen = windowsize + horizon

validsegments = segmentsizes.loc[segmentsizes["length"] >= minlen, "segmentid"]

dfvalid = df[df["segmentid"].isin(validsegments)].copy().reset_index(drop=True)

print("Shape dfvalid:", dfvalid.shape)
print("Segmenti validi:", dfvalid["segmentid"].nunique())
print("Lunghezza minima richiesta:", minlen)

featurecols = ["temp", "hum", "lux"]

X_seq = []
last_temp_list = []
future_temp_list = []
y_delta = []
metatime = []

for segid, segdf in dfvalid.groupby("segmentid"):
    segdf = segdf.sort_values("time").reset_index(drop=True)

    values = segdf[featurecols].values
    temps = segdf["temp"].values
    times = segdf["time"].values

    for i in range(len(segdf) - windowsize - horizon + 1):
        x_window = values[i:i + windowsize]
        last_temp = temps[i + windowsize - 1]
        future_temp = temps[i + windowsize + horizon - 1]
        delta_t = future_temp - last_temp

        X_seq.append(x_window)
        last_temp_list.append(last_temp)
        future_temp_list.append(future_temp)
        y_delta.append(delta_t)
        metatime.append(times[i + windowsize + horizon - 1])

X_seq = np.array(X_seq)
last_temp_arr = np.array(last_temp_list)
future_temp_arr = np.array(future_temp_list)
y_delta = np.array(y_delta)
metatime = np.array(metatime)

print("Shape X_seq:", X_seq.shape)
print("Shape y_delta:", y_delta.shape)
print("Prime 5 delta:", y_delta[:5])

Xflat = X_seq.reshape(X_seq.shape[0], X_seq.shape[1] * X_seq.shape[2])

print("Shape Xflat:", Xflat.shape)

splitidx = int(len(Xflat) * 0.8)

Xtrain = Xflat[:splitidx]
Xtest = Xflat[splitidx:]

Xtrain_seq = X_seq[:splitidx]
Xtest_seq = X_seq[splitidx:]

ytrain_delta = y_delta[:splitidx]
ytest_delta = y_delta[splitidx:]

last_temp_train = last_temp_arr[:splitidx]
last_temp_test = last_temp_arr[splitidx:]

future_temp_train = future_temp_arr[:splitidx]
future_temp_test = future_temp_arr[splitidx:]

timetrain = metatime[:splitidx]
timetest = metatime[splitidx:]

print("Train classici:", Xtrain.shape, ytrain_delta.shape)
print("Test classici :", Xtest.shape, ytest_delta.shape)
print("Train seq     :", Xtrain_seq.shape, ytrain_delta.shape)
print("Test seq      :", Xtest_seq.shape, ytest_delta.shape)

# =========================================================
# metriche di valutazione
# =========================================================

def regression_metrics(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    return mae, rmse, r2

# =========================================================
# Baseline naive sul delta
# =========================================================

naive_delta_pred = np.zeros_like(ytest_delta)
naive_temp_pred = last_temp_test + naive_delta_pred

naive_mae, naive_rmse, naive_r2 = regression_metrics(future_temp_test, naive_temp_pred)

print("Naive baseline (delta = 0)")
print("MAE :", naive_mae)
print("RMSE:", naive_rmse)
print("R2  :", naive_r2)

# =========================================================
# Linear Regression sul delta
# =========================================================

lin_model = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LinearRegression())
])

lin_model.fit(Xtrain, ytrain_delta)
lin_delta_pred = lin_model.predict(Xtest)
lin_temp_pred = last_temp_test + lin_delta_pred

lin_mae, lin_rmse, lin_r2 = regression_metrics(future_temp_test, lin_temp_pred)

print("Linear Regression (delta)")
print("MAE :", lin_mae)
print("RMSE:", lin_rmse)
print("R2  :", lin_r2)

# =========================================================
# Ridge Regression sul delta
# =========================================================
from sklearn.linear_model import Ridge
ridge_model = Pipeline([
    ("scaler", StandardScaler()),
    ("model", Ridge(alpha=1.0))
])

ridge_model.fit(Xtrain, ytrain_delta)
ridge_delta_pred = ridge_model.predict(Xtest)
ridge_temp_pred = last_temp_test + ridge_delta_pred

ridge_mae, ridge_rmse, ridge_r2 = regression_metrics(future_temp_test, ridge_temp_pred)

print("Ridge Regression (delta)")
print("MAE :", ridge_mae)
print("RMSE:", ridge_rmse)
print("R2  :", ridge_r2)

# =========================================================
# Random Forest sul delta
# =========================================================

rf_model = RandomForestRegressor(
    n_estimators=300,
    max_depth=10,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(Xtrain, ytrain_delta)
rf_delta_pred = rf_model.predict(Xtest)
rf_temp_pred = last_temp_test + rf_delta_pred

rf_mae, rf_rmse, rf_r2 = regression_metrics(future_temp_test, rf_temp_pred)

print("Random Forest (delta)")
print("MAE :", rf_mae)
print("RMSE:", rf_rmse)
print("R2  :", rf_r2)

# =========================================================
# Gradient Boosting sul delta
# =========================================================
from sklearn.ensemble import  GradientBoostingRegressor
gbr_model = GradientBoostingRegressor(
    n_estimators=300,
    learning_rate=0.03,
    max_depth=3,
    random_state=42
)

gbr_model.fit(Xtrain, ytrain_delta)
gbr_delta_pred = gbr_model.predict(Xtest)
gbr_temp_pred = last_temp_test + gbr_delta_pred

gbr_mae, gbr_rmse, gbr_r2 = regression_metrics(future_temp_test, gbr_temp_pred)

print("Gradient Boosting (delta)")
print("MAE :", gbr_mae)
print("RMSE:", gbr_rmse)
print("R2  :", gbr_r2)

# =========================================================
# MLP sul delta
# =========================================================

mlp_model = Pipeline([
    ("scaler", StandardScaler()),
    ("model", MLPRegressor(
        hidden_layer_sizes=(128, 64),
        activation="relu",
        solver="adam",
        alpha=1e-4,
        learning_rate_init=1e-3,
        max_iter=500,
        early_stopping=True,
        validation_fraction=0.1,
        n_iter_no_change=20,
        random_state=42
    ))
])

mlp_model.fit(Xtrain, ytrain_delta)
mlp_delta_pred = mlp_model.predict(Xtest)
mlp_temp_pred = last_temp_test + mlp_delta_pred

mlp_mae, mlp_rmse, mlp_r2 = regression_metrics(future_temp_test, mlp_temp_pred)

print("MLP (delta)")
print("MAE :", mlp_mae)
print("RMSE:", mlp_rmse)
print("R2  :", mlp_r2)

# =========================================================
# LSTM sul delta
# =========================================================

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

n_features = Xtrain_seq.shape[2]

x_scaler = StandardScaler()
Xtrain_2d = Xtrain_seq.reshape(-1, n_features)
Xtest_2d = Xtest_seq.reshape(-1, n_features)

Xtrain_scaled = x_scaler.fit_transform(Xtrain_2d).reshape(Xtrain_seq.shape)
Xtest_scaled = x_scaler.transform(Xtest_2d).reshape(Xtest_seq.shape)

y_scaler = StandardScaler()
ytrain_delta_scaled = y_scaler.fit_transform(ytrain_delta.reshape(-1, 1)).ravel()
ytest_delta_scaled = y_scaler.transform(ytest_delta.reshape(-1, 1)).ravel()

tf.random.set_seed(42)
np.random.seed(42)

lstm_model = Sequential([
    Input(shape=(Xtrain_scaled.shape[1], Xtrain_scaled.shape[2])),
    LSTM(64),
    Dropout(0.2),
    Dense(32, activation="relu"),
    Dense(1)
])

lstm_model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=15,
    restore_best_weights=True
)

history = lstm_model.fit(
    Xtrain_scaled,
    ytrain_delta_scaled,
    validation_split=0.1,
    epochs=100,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

lstm_delta_pred_scaled = lstm_model.predict(Xtest_scaled).ravel()
lstm_delta_pred = y_scaler.inverse_transform(lstm_delta_pred_scaled.reshape(-1, 1)).ravel()
lstm_temp_pred = last_temp_test + lstm_delta_pred

lstm_mae, lstm_rmse, lstm_r2 = regression_metrics(future_temp_test, lstm_temp_pred)

print("LSTM (delta)")
print("MAE :", lstm_mae)
print("RMSE:", lstm_rmse)
print("R2  :", lstm_r2)

# =========================================================
# Comparazione risultati
# =========================================================

results_df = pd.DataFrame([
    {"model": "NaiveLastTemp",      "mae": naive_mae,  "rmse": naive_rmse,  "r2": naive_r2},
    {"model": "LinearRegressionΔ",  "mae": lin_mae,    "rmse": lin_rmse,    "r2": lin_r2},
    {"model": "RidgeΔ",             "mae": ridge_mae,  "rmse": ridge_rmse,  "r2": ridge_r2},
    {"model": "RandomForestΔ",      "mae": rf_mae,     "rmse": rf_rmse,     "r2": rf_r2},
    {"model": "GradientBoostingΔ",  "mae": gbr_mae,    "rmse": gbr_rmse,    "r2": gbr_r2},
    {"model": "MLPΔ",               "mae": mlp_mae,    "rmse": mlp_rmse,    "r2": mlp_r2},
    {"model": "LSTMΔ",              "mae": lstm_mae,   "rmse": lstm_rmse,   "r2": lstm_r2},
]).sort_values("rmse").reset_index(drop=True)

results_df