# -*- coding: utf-8 -*-
"""Test_ML_followingmeasure.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KOPov-gVCTsQVe91LsiTntbvQftwH15c
"""

!pip -q install pandas numpy scikit-learn matplotlib seaborn

import io
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

uploaded = files.upload()

filename = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[filename]))
df.head()

print(df.shape)
print(df.columns.tolist())
df.info()

df["time"] = pd.to_datetime(df["time"], utc=True)
df = df.sort_values("time").reset_index(drop=True)
df.head()

df.isna().sum()

df["delta_min"] = df["time"].diff().dt.total_seconds() / 60
df[["time", "delta_min"]].head(10)

df["delta_min"].value_counts(dropna=False).sort_index()

allowed_steps = {5, 10, 15}

df["delta_min_rounded"] = df["delta_min"].round().fillna(5)
df["isgap"] = ~df["delta_min_rounded"].isin(allowed_steps)
df["segmentid"] = df["isgap"].cumsum()

segment_sizes = df.groupby("segmentid").size().reset_index(name="length")
segment_sizes.sort_values("length", ascending=False).head(20)

min_len = 31
valid_segments = segment_sizes.loc[segment_sizes["length"] >= min_len, "segmentid"]
df_valid = df[df["segmentid"].isin(valid_segments)].copy().reset_index(drop=True)

print(df_valid.shape)
print(df_valid["segmentid"].nunique())

window_size = 30
horizon = 1

feature_cols = ["temp", "hum", "lux"]
target_col = "temp"

X, y, meta_time = [], [], []

for seg_id, seg_df in df_valid.groupby("segmentid"):
    seg_df = seg_df.sort_values("time").reset_index(drop=True)
    values = seg_df[feature_cols].values
    target = seg_df[target_col].values
    times = seg_df["time"].values

    for i in range(len(seg_df) - window_size - horizon + 1):
        X.append(values[i:i+window_size])
        y.append(target[i+window_size+horizon-1])
        meta_time.append(times[i+window_size+horizon-1])

X = np.array(X)
y = np.array(y)
meta_time = np.array(meta_time)

print("Shape di X:", X.shape)
print("Shape di y:", y.shape)

X_flat = X.reshape(X.shape[0], X.shape[1] * X.shape[2])
print("Shape di X_flat:", X_flat.shape)

split_idx = int(len(X_flat) * 0.8)

X_train, X_test = X_flat[:split_idx], X_flat[split_idx:]
y_train, y_test = y[:split_idx], y[split_idx:]
time_train, time_test = meta_time[:split_idx], meta_time[split_idx:]

print("Train:", X_train.shape, y_train.shape)
print("Test:", X_test.shape, y_test.shape)

naive_preds = X_test[:, (window_size - 1) * 3 + 0]

# =========================================================
# metriche di valutazione
# =========================================================

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def regression_metrics(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    return mae, rmse, r2

# =========================================================
# Baseline Naive
# =========================================================

naive_mae, naive_rmse, naive_r2 = regression_metrics(y_test, naive_preds)

print("Naive baseline")
print("MAE :", naive_mae)
print("RMSE:", naive_rmse)
print("R2  :", naive_r2)

# =========================================================
# Linear Regression
# =========================================================

from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

lin_model = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LinearRegression())
])

lin_model.fit(X_train, y_train)
lin_preds = lin_model.predict(X_test)

lin_mae, lin_rmse, lin_r2 = regression_metrics(y_test, lin_preds)

print("Linear Regression")
print("MAE :", lin_mae)
print("RMSE:", lin_rmse)
print("R2  :", lin_r2)

# =========================================================
# Random Forest
# =========================================================

from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=300,
    max_depth=10,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)
rf_preds = rf_model.predict(X_test)

rf_mae, rf_rmse, rf_r2 = regression_metrics(y_test, rf_preds)

print("Random Forest")
print("MAE :", rf_mae)
print("RMSE:", rf_rmse)
print("R2  :", rf_r2)

# =========================================================
# Ridge Regression
# =========================================================

from sklearn.linear_model import Ridge
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

ridge_model = Pipeline([
    ("scaler", StandardScaler()),
    ("model", Ridge(alpha=1.0))
])

ridge_model.fit(X_train, y_train)
ridge_preds = ridge_model.predict(X_test)

ridge_mae, ridge_rmse, ridge_r2 = regression_metrics(y_test, ridge_preds)

print("Ridge Regression")
print("MAE :", ridge_mae)
print("RMSE:", ridge_rmse)
print("R2  :", ridge_r2)

# =========================================================
# Gradient Boosting
# =========================================================

from sklearn.ensemble import GradientBoostingRegressor

gbr_model = GradientBoostingRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

gbr_model.fit(X_train, y_train)
gbr_preds = gbr_model.predict(X_test)

gbr_mae, gbr_rmse, gbr_r2 = regression_metrics(y_test, gbr_preds)

print("Gradient Boosting")
print("MAE :", gbr_mae)
print("RMSE:", gbr_rmse)
print("R2  :", gbr_r2)

# =========================================================
# MLP
# =========================================================

from sklearn.neural_network import MLPRegressor

mlp_model = Pipeline([
    ("scaler", StandardScaler()),
    ("model", MLPRegressor(
        hidden_layer_sizes=(128, 64),
        activation="relu",
        solver="adam",
        alpha=1e-4,
        learning_rate_init=1e-3,
        max_iter=500,
        early_stopping=True,
        validation_fraction=0.1,
        n_iter_no_change=20,
        random_state=42
    ))
])

mlp_model.fit(X_train, y_train)
mlp_preds = mlp_model.predict(X_test)

mlp_mae, mlp_rmse, mlp_r2 = regression_metrics(y_test, mlp_preds)

print("MLP")
print("MAE :", mlp_mae)
print("RMSE:", mlp_rmse)
print("R2  :", mlp_r2)

# =========================
# LSTM
# =========================

!pip -q install tensorflow

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

split_idx = int(len(X) * 0.8)

X_train_lstm, X_test_lstm = X[:split_idx], X[split_idx:]
y_train_lstm, y_test_lstm = y[:split_idx], y[split_idx:]

print("Train LSTM:", X_train_lstm.shape, y_train_lstm.shape)
print("Test LSTM:", X_test_lstm.shape, y_test_lstm.shape)

n_features = X_train_lstm.shape[2]

x_scaler = StandardScaler()
X_train_2d = X_train_lstm.reshape(-1, n_features)
X_test_2d = X_test_lstm.reshape(-1, n_features)

X_train_scaled = x_scaler.fit_transform(X_train_2d).reshape(X_train_lstm.shape)
X_test_scaled = x_scaler.transform(X_test_2d).reshape(X_test_lstm.shape)

y_scaler = StandardScaler()
y_train_scaled = y_scaler.fit_transform(y_train_lstm.reshape(-1, 1)).ravel()
y_test_scaled = y_scaler.transform(y_test_lstm.reshape(-1, 1)).ravel()

tf.random.set_seed(42)
np.random.seed(42)

lstm_model = Sequential([
    LSTM(64, input_shape=(X_train_scaled.shape[1], X_train_scaled.shape[2])),
    Dropout(0.2),
    Dense(32, activation="relu"),
    Dense(1)
])

lstm_model.compile(optimizer="adam", loss="mse", metrics=["mae"])

early_stop = EarlyStopping(monitor="val_loss", patience=15, restore_best_weights=True)

history = lstm_model.fit(
    X_train_scaled,
    y_train_scaled,
    validation_split=0.1,
    epochs=100,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

lstm_preds_scaled = lstm_model.predict(X_test_scaled).ravel()
lstm_preds = y_scaler.inverse_transform(lstm_preds_scaled.reshape(-1, 1)).ravel()

lstm_mae = mean_absolute_error(y_test_lstm, lstm_preds)
lstm_rmse = np.sqrt(mean_squared_error(y_test_lstm, lstm_preds))
lstm_r2 = r2_score(y_test_lstm, lstm_preds)

print("LSTM")
print("MAE :", lstm_mae)
print("RMSE:", lstm_rmse)
print("R2  :", lstm_r2)

# =========================================================
# Comparazione risultati
# =========================================================

results_df = pd.DataFrame([
    {"model": "NaiveLastTemp",      "mae": naive_mae,  "rmse": naive_rmse,  "r2": naive_r2},
    {"model": "LinearRegression",   "mae": lin_mae,    "rmse": lin_rmse,    "r2": lin_r2},
    {"model": "Ridge",              "mae": ridge_mae,  "rmse": ridge_rmse,  "r2": ridge_r2},
    {"model": "RandomForest",       "mae": rf_mae,     "rmse": rf_rmse,     "r2": rf_r2},
    {"model": "GradientBoosting",   "mae": gbr_mae,    "rmse": gbr_rmse,    "r2": gbr_r2},
    {"model": "MLP",                "mae": mlp_mae,    "rmse": mlp_rmse,    "r2": mlp_r2},
    {"model": "LTSM",                "mae": lstm_mae,    "rmse": lstm_rmse,    "r2": lstm_r2},
]).sort_values("rmse").reset_index(drop=True)

display(results_df)